server:
  port: 8080

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

file:
  upload:
    path: ./data/images/
